server:
  port: 8040

spring:
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: false
    virtual-host: /
logging:
  config: classpath:logback-boot.xml